name: BUILD CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: philo
      run: make

  build_bonus:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: philo_bonus
      run: make
